doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            remote:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL_REMOTE)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default

        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    string_functions:
                        MATCH_AGAINST: App\Extensions\Doctrine\MatchAgainst
                        DATE: DoctrineExtensions\Query\Mysql\Date
                    numeric_functions:
                        RAND: App\Extensions\Doctrine\Rand

            remote:
                connection: remote
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    string_functions:
                        MATCH_AGAINST: App\Extensions\Doctrine\MatchAgainst
                        DATE: DoctrineExtensions\Query\Mysql\Date
                    numeric_functions:
                        RAND: App\Extensions\Doctrine\Rand